// agentguard deepagents-init — set up LangChain DeepAgents integration
// Writes an AgentGuard middleware shim to .deepagents/agentguard_middleware.py (repo-level)
// or ~/.deepagents/agentguard_middleware.py (global).
// The middleware calls agentguard deepagents-hook via subprocess for before/after hooks.

import { readFileSync, writeFileSync, existsSync, mkdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { RESET, BOLD, DIM, FG } from '../colors.js';
import { resolveMainRepoRoot } from '@red-codes/core';
import type { EnforcementMode } from '@red-codes/core';

import { resolveBinary } from '../resolve-binary.js';

const HOOK_MARKER = 'deepagents-hook';

/** Detect if we're in the agentguard development repo (local dev) vs. globally installed. */
function resolveCliPrefix(isGlobal: boolean): { cli: string; isLocal: boolean } {
  const resolved = resolveBinary(isGlobal);
  return { cli: resolved.cli, isLocal: resolved.isLocal };
}

/**
 * Generate the Python middleware file content for DeepAgents.
 * DeepAgents uses Python middleware objects injected into create_deep_agent().
 * This shim calls agentguard via subprocess on each tool invocation.
 */
function generateMiddlewareContent(cli: string, storeSuffix: string, dbPathSuffix: string): string {
  return `# AgentGuard governance middleware for LangChain DeepAgents
# Auto-generated by: agentguard deepagents-init
# Inject this middleware into your create_deep_agent() call.
# Docs: https://github.com/AgentGuardHQ/agent-guard

import json
import subprocess
import os


class AgentGuardMiddleware:
    """AgentGuard governance middleware for DeepAgents tool calls.

    Intercepts all tool invocations before and after execution,
    routing them through the AgentGuard governance kernel for
    policy and invariant enforcement.

    Usage:
        from .deepagents.agentguard_middleware import AgentGuardMiddleware

        agent = create_deep_agent(
            middleware=[AgentGuardMiddleware()],
            ...
        )
    """

    name = "agentguard"

    def before(self, tool: str, input: dict) -> None:
        """Intercept tool call before execution. Raises if policy denies."""
        try:
            payload = json.dumps({"tool": tool, "input": input})
            result = subprocess.run(
                "${cli} ${HOOK_MARKER} before${storeSuffix}${dbPathSuffix}".split(),
                input=payload,
                capture_output=True,
                text=True,
                timeout=30,
            )
            output = result.stdout.strip()
            if output:
                parsed = json.loads(output)
                if parsed.get("decision") == "deny":
                    raise PermissionError(
                        f"AgentGuard blocked: {parsed.get('reason', 'policy violation')}"
                    )
        except PermissionError:
            raise
        except Exception:
            # Governance check failed — fail open to avoid blocking the agent
            pass

    def after(self, tool: str, input: dict, output) -> None:
        """Report tool execution result for audit trail."""
        try:
            payload = json.dumps({"tool": tool, "input": input, "output": output})
            subprocess.run(
                "${cli} ${HOOK_MARKER} after${storeSuffix}${dbPathSuffix}".split(),
                input=payload,
                capture_output=True,
                text=True,
                timeout=10,
            )
        except Exception:
            # Non-fatal
            pass
`;
}

const POLICY_CANDIDATES = [
  'agentguard.yaml',
  'agentguard.yml',
  'agentguard.json',
  '.agentguard.yaml',
  '.agentguard.yml',
];

const STARTER_POLICY_TEMPLATE = (
  mode: EnforcementMode
) => `# AgentGuard policy — safety rules for AI coding agents.
# Customize this file to match your project's security requirements.
# Docs: https://github.com/AgentGuardHQ/agent-guard

id: default-policy
name: Default Safety Policy
description: Baseline safety rules for AI coding agents
severity: 4

# Enforcement mode: guide | educate | monitor | enforce
#   guide   — block dangerous actions with corrective suggestions (recommended)
#   educate — allow actions but teach correct patterns
#   monitor — log threats, don't block
#   enforce — block dangerous actions, no suggestions
mode: ${mode}

rules:
  # Protected branches — prevent direct push to main/master
  - action: git.push
    effect: deny
    branches: [main, master]
    reason: Direct push to protected branch
    suggestion: Push to a feature branch and open a pull request instead
    correctedCommand: "git push origin HEAD:feat/my-branch"

  # No force push — prevent history rewriting
  - action: git.force-push
    effect: deny
    reason: Force push rewrites shared history

  # Secrets protection — block writes to sensitive files
  - action: file.write
    effect: deny
    target: .env
    reason: Secrets files must not be modified

  - action: file.write
    effect: deny
    target: ".npmrc"
    reason: npm credentials file must not be modified by agents

  # Destructive command protection
  - action: shell.exec
    effect: deny
    target: rm -rf
    reason: Destructive shell commands blocked

  # Deployment protection
  - action: deploy.trigger
    effect: deny
    reason: Deploy actions require explicit authorization

  - action: infra.destroy
    effect: deny
    reason: Infrastructure destruction requires explicit authorization

  # Defaults
  - action: file.read
    effect: allow
    reason: Reading is always safe

  - action: file.write
    effect: allow
    reason: File writes allowed by default
`;

function generateStarterPolicy(mode: EnforcementMode = 'guide'): boolean {
  const repoRoot = resolveMainRepoRoot();
  for (const candidate of POLICY_CANDIDATES) {
    if (existsSync(join(repoRoot, candidate))) {
      return false;
    }
  }
  const policyPath = join(repoRoot, 'agentguard.yaml');
  writeFileSync(policyPath, STARTER_POLICY_TEMPLATE(mode), 'utf8');
  process.stderr.write(
    `  ${FG.green}\u2713${RESET}  Policy created: ${FG.cyan}agentguard.yaml${RESET} (${mode} mode)\n`
  );
  return true;
}

function showProtectionSummary(policyGenerated: boolean, mode: EnforcementMode = 'guide'): void {
  process.stderr.write('\n');
  process.stderr.write(`  ${FG.green}${BOLD}AgentGuard is active for DeepAgents.${RESET}\n\n`);

  if (mode === 'guide') {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.cyan}guide${RESET}${BOLD} — dangerous actions blocked with corrective suggestions${RESET}\n\n`
    );
  } else if (mode === 'educate') {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.blue}educate${RESET}${BOLD} — actions allowed with corrective teaching${RESET}\n\n`
    );
  } else if (mode === 'monitor') {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.yellow}monitor${RESET}${BOLD} — threats are logged, not blocked${RESET}\n\n`
    );
  } else {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.red}enforce${RESET}${BOLD} — dangerous actions are blocked${RESET}\n\n`
    );
  }

  process.stderr.write(
    `  ${FG.blue}\u25A0${RESET} ${DIM}Track${RESET} all actions with audit trail\n`
  );
  process.stderr.write('\n');

  process.stderr.write(`  ${BOLD}Next steps:${RESET}\n`);
  if (policyGenerated) {
    process.stderr.write(
      `  ${DIM}1. Edit ${FG.cyan}agentguard.yaml${RESET}${DIM} to customize rules for your project${RESET}\n`
    );
    process.stderr.write(
      `  ${DIM}2. Import AgentGuardMiddleware in your DeepAgents setup script${RESET}\n`
    );
    process.stderr.write(
      `  ${DIM}3. Run ${FG.cyan}agentguard inspect --last${RESET}${DIM} to review decisions${RESET}\n`
    );
  } else {
    process.stderr.write(
      `  ${DIM}1. Import AgentGuardMiddleware in your DeepAgents setup script${RESET}\n`
    );
    process.stderr.write(
      `  ${DIM}2. Run ${FG.cyan}agentguard inspect --last${RESET}${DIM} to review decisions${RESET}\n`
    );
  }
  process.stderr.write(
    `\n  ${DIM}Remove: ${FG.cyan}agentguard deepagents-init --remove${RESET}\n\n`
  );
}

function removeMiddleware(middlewarePath: string, middlewareLabel: string): void {
  if (!existsSync(middlewarePath)) {
    process.stderr.write(
      `  ${FG.yellow}Not installed.${RESET} No AgentGuard middleware found at ${middlewareLabel}.\n\n`
    );
    return;
  }
  try {
    const content = readFileSync(middlewarePath, 'utf8');
    if (!content.includes(HOOK_MARKER)) {
      process.stderr.write(
        `  ${FG.yellow}Skipped.${RESET} File at ${middlewareLabel} was not created by agentguard.\n\n`
      );
      return;
    }
    unlinkSync(middlewarePath);
    process.stderr.write(`  ${FG.green}\u2713${RESET}  Removed: ${middlewareLabel}\n\n`);
  } catch {
    process.stderr.write(`  ${FG.red}\u2717${RESET}  Failed to remove ${middlewareLabel}.\n\n`);
  }
}

export async function deepAgentsInit(args: string[] = []): Promise<void> {
  const isGlobal = args.includes('--global') || args.includes('-g');
  const isRemove = args.includes('--remove') || args.includes('--uninstall');

  const storeIdx = args.findIndex((a) => a === '--store');
  const storeBackend = storeIdx !== -1 ? args[storeIdx + 1] : undefined;
  const storeSuffix = storeBackend ? ` --store ${storeBackend}` : '';

  const dbPathIdx = args.findIndex((a) => a === '--db-path');
  const dbPathValue = dbPathIdx !== -1 ? args[dbPathIdx + 1] : undefined;
  const dbPathSuffix = dbPathValue ? ` --db-path "${dbPathValue}"` : '';

  const modeArgIdx = args.findIndex((a) => a === '--mode');
  const modeArg = modeArgIdx !== -1 ? args[modeArgIdx + 1] : undefined;
  const VALID_MODES: EnforcementMode[] = ['guide', 'educate', 'monitor', 'enforce'];
  const selectedMode: EnforcementMode =
    modeArg && VALID_MODES.includes(modeArg as EnforcementMode)
      ? (modeArg as EnforcementMode)
      : 'guide';

  // DeepAgents middleware location:
  // Repo-level: .deepagents/agentguard_middleware.py
  // Global: ~/.deepagents/agentguard_middleware.py
  const middlewareDir = isGlobal
    ? join(homedir(), '.deepagents')
    : join(process.cwd(), '.deepagents');
  const middlewarePath = join(middlewareDir, 'agentguard_middleware.py');
  const middlewareLabel = isGlobal
    ? '~/.deepagents/agentguard_middleware.py'
    : '.deepagents/agentguard_middleware.py';

  process.stderr.write('\n');
  process.stderr.write(`  ${BOLD}AgentGuard DeepAgents Integration${RESET}\n\n`);

  if (isRemove) {
    removeMiddleware(middlewarePath, middlewareLabel);
    return;
  }

  if (!existsSync(middlewareDir)) {
    mkdirSync(middlewareDir, { recursive: true });
  }

  if (existsSync(middlewarePath)) {
    try {
      const content = readFileSync(middlewarePath, 'utf8');
      if (content.includes(HOOK_MARKER)) {
        process.stderr.write(
          `  ${FG.yellow}Already configured.${RESET} AgentGuard middleware found at ${middlewareLabel}.\n`
        );
        process.stderr.write(`  ${DIM}Use --remove to uninstall.${RESET}\n\n`);
        return;
      }
    } catch {
      // Unreadable — overwrite
    }
  }

  const { cli } = resolveCliPrefix(isGlobal);
  const middlewareContent = generateMiddlewareContent(cli, storeSuffix, dbPathSuffix);
  writeFileSync(middlewarePath, middlewareContent, 'utf8');

  process.stderr.write(
    `  ${FG.green}\u2713${RESET}  Middleware created: ${FG.cyan}${middlewareLabel}${RESET}\n`
  );

  const policyGenerated = generateStarterPolicy(selectedMode);
  showProtectionSummary(policyGenerated, selectedMode);
}
