// CLI command: agentguard learn — analyze denial patterns across sessions and suggest policy improvements.
// Inspired by RTK's correction learning: detect frustrated agent loops, classify resolutions,
// generate actionable governance hints.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseArgs } from '../args.js';
import type { StorageConfig } from '@red-codes/storage';

// ---------------------------------------------------------------------------
// ANSI colors
// ---------------------------------------------------------------------------

const ANSI = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  magenta: '\x1b[35m',
};

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

function confidenceColor(confidence: number): string {
  if (confidence >= 0.8) return ANSI.green;
  if (confidence >= 0.6) return ANSI.yellow;
  return ANSI.red;
}

function resolutionLabel(resolution: string): string {
  switch (resolution) {
    case 'retried_differently':
      return `${ANSI.yellow}retried differently${ANSI.reset}`;
    case 'session_abandoned':
      return `${ANSI.red}session abandoned${ANSI.reset}`;
    case 'escalation_granted':
      return `${ANSI.cyan}escalation granted${ANSI.reset}`;
    default:
      return resolution;
  }
}

function suggestionTypeLabel(type: string): string {
  switch (type) {
    case 'allow_rule':
      return `${ANSI.green}allow_rule${ANSI.reset}`;
    case 'scope_expansion':
      return `${ANSI.yellow}scope_expansion${ANSI.reset}`;
    case 'threshold_adjustment':
      return `${ANSI.cyan}threshold_adjustment${ANSI.reset}`;
    case 'working_as_intended':
      return `${ANSI.dim}working_as_intended${ANSI.reset}`;
    default:
      return type;
  }
}

// ---------------------------------------------------------------------------
// Governance hints markdown generation
// ---------------------------------------------------------------------------

function generateGovernanceHints(
  patterns: import('@red-codes/storage').DenialPattern[],
  suggestions: import('@red-codes/storage').PolicySuggestion[]
): string {
  const lines: string[] = [
    '# AgentGuard Governance Hints',
    '<!-- Auto-generated by agentguard learn — do not edit manually -->',
    '',
  ];

  if (patterns.length === 0) {
    lines.push('No denial patterns detected across recorded sessions.');
    lines.push('');
    return lines.join('\n');
  }

  lines.push('## Denied Patterns');
  lines.push('');

  for (const pattern of patterns) {
    const sessionCount = pattern.sessions.length;
    lines.push(
      `- **${pattern.actionType}** denied for "${pattern.reason}" ` +
        `(${pattern.occurrences} occurrences, ${sessionCount} session${sessionCount !== 1 ? 's' : ''})`
    );

    if (pattern.suggestion) {
      lines.push(`  - Suggestion: ${pattern.suggestion}`);
    } else {
      // Auto-generate suggestion text from resolution
      switch (pattern.resolution) {
        case 'retried_differently':
          lines.push(
            `  - Suggestion: Review the \`${pattern.actionType}\` deny rule — agents consistently retry with different parameters`
          );
          break;
        case 'session_abandoned':
          lines.push(
            `  - Note: Sessions end after this denial — policy may be working as intended or too restrictive`
          );
          break;
        case 'escalation_granted':
          lines.push(
            `  - Suggestion: Consider pre-authorizing \`${pattern.actionType}\` under specific conditions to reduce escalation overhead`
          );
          break;
      }
    }
  }

  lines.push('');

  if (suggestions.length > 0) {
    lines.push('## Recommendations');
    lines.push('');

    for (const suggestion of suggestions) {
      lines.push(`- ${suggestion.description}`);
    }

    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Terminal output rendering
// ---------------------------------------------------------------------------

function renderLearningReport(
  patterns: import('@red-codes/storage').DenialPattern[],
  suggestions: import('@red-codes/storage').PolicySuggestion[],
  sessionCount: number
): void {
  process.stderr.write('\n');
  process.stderr.write(`  ${ANSI.bold}Denial Pattern Analysis${ANSI.reset}\n`);
  process.stderr.write(`  ${ANSI.dim}${'─'.repeat(60)}${ANSI.reset}\n`);
  process.stderr.write('\n');

  if (patterns.length === 0) {
    process.stderr.write(
      `  ${ANSI.dim}No denial patterns found across ${sessionCount} session(s).${ANSI.reset}\n\n`
    );
    return;
  }

  process.stderr.write(
    `  ${ANSI.bold}${patterns.length} pattern(s)${ANSI.reset} detected across ` +
      `${sessionCount} session(s)\n\n`
  );

  process.stderr.write(`  ${ANSI.bold}Denied Patterns${ANSI.reset}\n`);
  process.stderr.write(`  ${ANSI.dim}${'─'.repeat(40)}${ANSI.reset}\n`);

  for (const pattern of patterns) {
    const cc = confidenceColor(pattern.confidence);
    const sessionLabel =
      pattern.sessions.length === 1 ? '1 session' : `${pattern.sessions.length} sessions`;

    process.stderr.write(
      `\n  ${ANSI.bold}${pattern.actionType}${ANSI.reset} — ${ANSI.dim}"${pattern.reason}"${ANSI.reset}\n`
    );
    process.stderr.write(`    Occurrences:  ${pattern.occurrences}  (${sessionLabel})\n`);
    process.stderr.write(`    Resolution:   ${resolutionLabel(pattern.resolution)}\n`);
    process.stderr.write(
      `    Confidence:   ${cc}${(pattern.confidence * 100).toFixed(0)}%${ANSI.reset}\n`
    );
  }

  process.stderr.write('\n');

  if (suggestions.length > 0) {
    process.stderr.write(`  ${ANSI.bold}Policy Suggestions${ANSI.reset}\n`);
    process.stderr.write(`  ${ANSI.dim}${'─'.repeat(40)}${ANSI.reset}\n`);

    for (const suggestion of suggestions) {
      const cc = confidenceColor(suggestion.confidence);
      process.stderr.write(
        `\n  ${ANSI.magenta}[${suggestion.actionType}]${ANSI.reset} ${suggestionTypeLabel(suggestion.type)}\n`
      );
      process.stderr.write(`    ${ANSI.dim}${suggestion.description}${ANSI.reset}\n`);
      process.stderr.write(
        `    Confidence: ${cc}${(suggestion.confidence * 100).toFixed(0)}%${ANSI.reset}\n`
      );
    }

    process.stderr.write('\n');
  } else {
    process.stderr.write(
      `  ${ANSI.dim}No actionable suggestions at current confidence thresholds.${ANSI.reset}\n\n`
    );
  }
}

// ---------------------------------------------------------------------------
// Public command
// ---------------------------------------------------------------------------

export async function learn(args: string[]): Promise<number> {
  const parsed = parseArgs(args, {
    boolean: ['--write-rules', '--json', '--help', '-h'],
    string: ['--store', '--db-path'],
  });

  const writeRules = parsed.flags['write-rules'] === true;
  const jsonOutput = parsed.flags['json'] === true;
  const dbPathFlag = parsed.flags['db-path'] as string | undefined;

  const storageConfig: StorageConfig = {
    backend: 'sqlite',
    dbPath: dbPathFlag ?? process.env['AGENTGUARD_DB_PATH'],
  };

  // 1. Load ACTION_DENIED events and all events from SQLite
  const { createStorageBundle, queryEventsByKindAcrossRuns, analyzeDenialPatterns } =
    await import('@red-codes/storage');

  let rawDeniedEvents: Array<{
    kind: string;
    actionType?: string;
    timestamp?: number;
    runId?: string;
    reason?: string;
    target?: string;
    policyRule?: string;
    invariant?: string;
  }> = [];

  let allCrossRunEvents: Array<{
    kind: string;
    actionType?: string;
    timestamp?: number;
    runId?: string;
  }> = [];

  let distinctSessions = 0;

  try {
    const storage = await createStorageBundle(storageConfig);

    if (storage.db) {
      const db = storage.db as import('better-sqlite3').Database;

      // Load denial events
      rawDeniedEvents = queryEventsByKindAcrossRuns(db, 'ActionDenied');

      // Load companion events for resolution classification
      const allowed = queryEventsByKindAcrossRuns(db, 'ActionAllowed');
      const escalated = queryEventsByKindAcrossRuns(db, 'ActionEscalated');
      allCrossRunEvents = [...rawDeniedEvents, ...allowed, ...escalated];

      // Count distinct sessions
      const sessionIds = new Set(rawDeniedEvents.map((e) => e.runId).filter(Boolean));
      distinctSessions = sessionIds.size;

      storage.close();
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`  Error loading governance events: ${msg}\n`);
    process.stderr.write(
      '  Ensure AgentGuard has recorded governance sessions (--store sqlite).\n\n'
    );
    return 1;
  }

  if (rawDeniedEvents.length === 0) {
    process.stderr.write('\n  No denial events found in governance database.\n');
    process.stderr.write('  Run `agentguard guard` to start recording governance events.\n\n');
    return 0;
  }

  // 2. Convert raw events to DenialEvent shape
  const denialEvents: import('@red-codes/storage').DenialEvent[] = rawDeniedEvents
    .filter((e) => e.actionType && e.timestamp !== undefined)
    .map((e) => ({
      actionType: e.actionType!,
      reason: extractDenialReason(e),
      timestamp: e.timestamp!,
      runId: e.runId ?? 'unknown',
      target: e.target,
      policyRule: e.policyRule,
      invariant: e.invariant,
    }));

  // 3. Run full analysis pipeline
  const { patterns, suggestions } = analyzeDenialPatterns(denialEvents, allCrossRunEvents);

  // 4. Output
  if (jsonOutput) {
    process.stdout.write(
      JSON.stringify({ patterns, suggestions, sessionCount: distinctSessions }, null, 2) + '\n'
    );
    return 0;
  }

  renderLearningReport(patterns, suggestions, distinctSessions);

  // 5. Optionally write governance hints
  if (writeRules) {
    const rulesDir = resolve('.claude', 'rules');
    const hintsPath = join(rulesDir, 'governance-hints.md');

    try {
      mkdirSync(rulesDir, { recursive: true });
      const markdown = generateGovernanceHints(patterns, suggestions);
      writeFileSync(hintsPath, markdown, 'utf8');
      process.stderr.write(`  Governance hints written to ${hintsPath}\n\n`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      process.stderr.write(`  Warning: could not write governance hints: ${msg}\n\n`);
    }
  } else if (patterns.length > 0) {
    process.stderr.write(
      `  ${ANSI.dim}Tip: Run ${ANSI.reset}${ANSI.cyan}agentguard learn --write-rules${ANSI.reset}` +
        `${ANSI.dim} to write governance hints to .claude/rules/governance-hints.md${ANSI.reset}\n\n`
    );
  }

  return 0;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Extract a human-readable denial reason from a raw event object.
 * Tries common field names used in AgentGuard governance events.
 */
function extractDenialReason(event: Record<string, unknown>): string {
  // Try direct fields first
  if (typeof event['reason'] === 'string') return event['reason'];
  if (typeof event['message'] === 'string') return event['message'];

  // Try nested payload/data objects
  const payload = event['payload'] ?? event['data'];
  if (payload && typeof payload === 'object') {
    const p = payload as Record<string, unknown>;
    if (typeof p['reason'] === 'string') return p['reason'];
    if (typeof p['message'] === 'string') return p['message'];
    if (typeof p['violation'] === 'string') return p['violation'];
  }

  // Try invariant/policy fields
  if (typeof event['invariant'] === 'string') return `invariant: ${event['invariant']}`;
  if (typeof event['policyRule'] === 'string') return `policy: ${event['policyRule']}`;

  return 'unknown reason';
}
